#!/usr/bin/env bash
#deploy="false"
deploy="true"

image=musicdoor
version=1.0
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t musicdoor/${image}:1.0 .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push musicdoor/${image}:1.0
    if [ "$latest" == "true" ]; then
        docker tag musicdoor/${image}:1.0 musicdoor/${image}:latest
        docker push musicdoor/${image}:latest
    fi
fi