#!/usr/bin/env bash
mvn clean package && docker build -t musicdoor/musicdoor .
docker rm -f musicdoor 2>/dev/null || true && docker run -d -p 8080:8080 -p 9990:9990 --name musicdoor musicdoor/musicdoor
